/*
Fichier procedures.sql
20140438 Legrand Marie
21505926 Di Giovanni Thomas
*/

alter SESSION set NLS_DATE_FORMAT = 'DD-MM-YYYY';

/* Procédures */
DELIMITER |
CREATE PROCEDURE TRAJETS_AVEC(IN user1 VARCHAR(30), IN user2 VARCHAR(30))
BEGIN

END |

CREATE PROCEDURE TENTATIVE_NOTE(IN user1 VARCHAR(30), IN user2 VARCHAR(30))
BEGIN
	IF exists(select * from  where )
		noter
	ELSE
		print no
END |

CREATE PROCEDURE 


/* Triggers */
CREATE TRIGGER UP_NBTRAJETS AFTER INSERT ON TRAJET
BEGIN
	
END |